name: Refresh database every 10 minutes
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  Redis-Update:
    runs-on: ubuntu-latest
    steps:
      - run: echo ">>> Fetching new contracts now ..."
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://clarity-search.dev/api/refresh"
          timeout: 15000
      - run: echo ">>> Contract uploading completed!"
