name: Refresh database every 30 minutes
on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  Redis-Update:
    runs-on: ubuntu-latest
    steps:
      - run: echo ">>> Fetching new contracts now ..."
      - name: Make request
        id: req
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://search-clarity.dev/api/refresh"
          timeout: 30000
      - name: Show counts
        run: echo ${{ steps.req.outputs.response.counts }}
      - run: echo ">>> Contract uploading completed!"
  Vercel-Redeploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo ">>> Trigger Vercel redeployment"
      - name: Make request
        id: reqver
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://api.vercel.com/v1/integrations/deploy/prj_wqBePRi7qg8kaN5pFW2kxNo8j0vu/aLf90LAx1H"
          timeout: 30000
      - name: Show counts
        run: echo ${{ steps.reqver.outputs.response.job.state }}
      - run: echo ">>> Redeploy initiated!"
